# Generated by Django 5.0.7 on 2024-07-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_configuracao_idioma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
    ]
